



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%Location: where there is a large number of refugee arrivals
location(ID,NumPeople).


%Collection Point: A structure which has the purpose of collecting, keeping goods and sorting them in the various shelters
collectionPoint(ID,People_Capacity,KM_Range).
%People_Capacity -> number of people which can be in the structure at the same time.
%KM_Range -> range of chilometers which has to be covered by the collection point

%https://en.wikipedia.org/wiki/Refugee_shelter#:~:text=Refugee%20shelters%20are%20structures%20ranging,kind%20of%20ad%20hoc%20structure.
%Shelter: A structure (e.g. tent or a building) which is a temporary residence for people who have lost or left their homes due to a natural disaster or war conflict
shelter(ID,People_Capacity).
%People_Capacity -> number of people which can be recieved in the structure at the same time.

%Group: A divison of people based on age, gender in a specific shelter.
group(ID_Group,ID_Shelter,Gender,L_Age,U_Age).
%A group is also characterized by an opened interval with two margins, L_Age and U_Age
%L_Age -> Lower Age Boundary
%U_Age -> Upper Age Boundary

%https://en.um.warszawa.pl/-/what-and-where-can-you-bring-for-refugees
%Company: Sells goods in at least one of the following categories (food,food for babies, personal hygiene products, baby products, medicine, first aid supplies, camping goods,clothes)
company(ID,Category).
%Category -> food, baby_food,personal_hygiene,baby_products,medicine,first_aid_supplies,camping_goods, clothes


%Each company has one or more offers with different prices and different type of goods.
foodOption(ID_Company,Expiration_Date,Price).
babyFoodOption(ID_Company,Expiration_Date,Price).
personalHygieneOption(ID_Company,Price).
babyProductsOption(ID_Company,Price).
medicine(ID_Company,Price).
firstAidSuppliesOption(ID_Company,Price).
campingGoodsOption(ID_Company,Price).
clothesOption(ID_Company,Price).

%Each Group of People has different needs and requiremenents
foodRequirement(Group_ID,Fats,Carbs,Proteins,Calories).
babyFoodRequirement(Group_ID,Fats,Carbs,Proteins,Calories).
clothesRequirement(Group_ID,Size,Type).
medicineRequirement(Group_ID,Name).


