



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%Location: where there is a large number of refugee arrivals
location(ID,NumPeople).


%Collection Point: A structure which has the purpose of collecting, keeping goods and sorting them in the various shelters
collectionPoint(ID,People_Capacity,KM_Range).
%People_Capacity -> number of people which can be in the structure at the same time.
%KM_Range -> range of chilometers which has to be covered by the collection point

%https://en.wikipedia.org/wiki/Refugee_shelter#:~:text=Refugee%20shelters%20are%20structures%20ranging,kind%20of%20ad%20hoc%20structure.
%Shelter: A structure (e.g. tent or a building) which is a temporary residence for people who have lost or left their homes due to a natural disaster or war conflict
shelter(ID,People_Capacity).
%People_Capacity -> number of people which can be recieved in the structure at the same time.

%Age Group: The suddivision of the population into different age groups.
ageGroup(ID,L_Age,U_Age).
%A group is also characterized by an opened interval with two margins, L_Age and U_Age
%L_Age -> lower bound of the age group
%U_Age -> upper bound of the age group

%Group: A divison of people based on age, gender
group(ID_Group,Gender,N_People,ID_Age_Group).

%https://en.um.warszawa.pl/-/what-and-where-can-you-bring-for-refugees
%Company: Sells goods in at least one of the following categories (food,food for babies, personal hygiene products, baby products, medicine, first aid supplies, camping goods,clothes)
company(ID,Category).
%Category -> food, baby_food,personal_hygiene,baby_products,medicine,first_aid_supplies,camping_goods, clothes


%Each company has one or more offers with different prices and different type of goods.
foodOption(ID_Company,Expiration_Date,Price).
babyFoodOption(ID_Company,Expiration_Date,Price).
personalHygieneOption(ID_Company,Price).
babyProductsOption(ID_Company,Price).
medicine(ID_Company,Price).
firstAidSuppliesOption(ID_Company,Price).
campingGoodsOption(ID_Company,Price).
clothesOption(ID_Company,Price).

%Each Group of People has different needs and requiremenents
foodRequirement(Group_ID,Fats,Carbs,Proteins,Calories).
babyFoodRequirement(Group_ID,Fats,Carbs,Proteins,Calories).
clothesRequirement(Group_ID,Size,Type).
medicineRequirement(Group_ID,Name).


%Rules for the system
%1. If a group is in a shelter, it cannot be in any other shelter
%2. The total number of people in a shelter cannot be greater than the capacity of the shelter
%3. It is preferred that groups with the same age group are in the same shelter (priority medium)
%4. It is preferred that the capacity of a shelter is used up before the next shelter is used (priority high)


% atoms
shelter(1,10).
shelter(2,5).

ageGroup(1,25,30).

group(1,male,5,1).


in(Group_ID,Shelter_ID) | out(Group_ID,Shelter_ID) :- group(Group_ID,_,_,_), shelter(Shelter_ID,_).

%1. If a group is in a shelter, it cannot be in any other shelter
:- in(Group_ID,Shelter_ID), in(Group_ID,Shelter_ID2), Shelter_ID != Shelter_ID2.
